// Settings

:doctype: article
:hyphens:
:icons: font
:lang: en
:listing-caption: Listing
:sectnums:
:source-highlighter: pygments
:xrefstyle: short

// Links

:url-win-7-sha1-values: https://answers.microsoft.com/en-us/windows/forum/windows_7-windows_install/how-to-obtain-a-windows-7-iso-file-to-create-an/59ef6586-f881-40b7-9070-e7950e057143
:url-win-7-x86: https://archive.org/details/Windows_7_Professional_SP1_x86.iso
:url-win-7-x64: https://archive.org/details/Windows_7_Professional_SP1_x64.iso

// Content

== Introduction

This repository provides a template for assessment 2, major exploitation task. The contents of the repository is listed in <<tab-layout>>.

[#tab-layout]
[cols="<20%,<80%", options="header"]
.Directory layout for submission.
|===
| Directory| Contents

| `/app`
| Source code for a vulnerable application.

| `/exploit`
| Python scripts, demonstrating bypass techniques for at least one security control.

|===

Tasks:

. Perform a `git clone` of the repository.

. Replace the contents with your vulnerable application, and retain the folder structure as per <<tab-layout>>.

. Write a https://makefiletutorial.com/[Makefile], which will be used to compile your vulnerable application.

. Provide instructions on how to build, execute, and exploit the application in <<sec-application>> and <<sec-exploit>>.

. Indicate in your submission the operating system and CPU architecture where your application should be built, and is vulnerable.

Restrictions:

* Your vulnerable application should compile and execute within an x86 or AMD64/Intel64 virtual machine. It is recommended you target either the https://kali.org/get-kali/#kali-virtual-machines[Kali Linux] 2021.2 or Windows 7 Professional (SP1) operating system.

* Alternatively, if targeting another operating system. Include a https://www.vagrantup.com/docs/vagrantfile[Vagrantfile] and provisioning scripts to build the virtual machine.

* Use https://asciidoctor.org/[Asciidoctor], or https://www.markdownguide.org/getting-started/[Markdown], to document your submission.

Tips:

* If not familiar with https://asciidoctor.org/[Asciidoctor] the document editor https://asciidocfx.com/[AsciidocFX] can help ensure the formatting of the document is valid.

* For https://www.markdownguide.org/getting-started/[Markdown], the visual editor https://typora.io[typora] provides a similar capability.

* Windows 7 Professional (SP1) ISO images are available to download for a {url-win-7-x86}[32-bit] or {url-win-7-x64}[64-bit] CPU architecture. The SHA1 hash values of these ISO images have been verified against values posted {url-win-7-sha1-values}[here].

[#sec-application]
== Application

James Evans - z3412483 (z3412483@ad.unsw.edu.au)

=== Dependencies

Building the application requires mingw-w64 package installed on a Linux build machine to compile.


=== Compiling

Run 'make clean' to remove the old .exe, and 'make' to create a new version of the cat_file.exe.

=== Execution

Place the .exe in the same location as where you're going to run the exploit.py, so the output exploit.txt is in the same directory.
When prompted, enter 'exploit.txt' as the input file.

[#sec-exploit]
== Exploit

=== Dependencies

Running the exploit requires python2.7 installed. 
Windows 7 Professional SP1 - with DEP _DISABLED_ 

=== Exploit 1

The program has SafeSEH, ASLR, NXCompact etc enabled on the libraries, but not on the base cat_file.exe.

Video Link of Exploit Demonstration: https://youtu.be/jgf8pKImmAE

1. Compile the cat_file.exe on linux with mingw-w64 package. '_Make clean_' removes the old .exe, '_make_' makes a new one.

2. Put the cat_file.exe on the Windows 7 SP1 Desktop

3. With Python2.7 run exploit.py. exploit.txt is generated.

4. Move exploit.txt to the desktop.

5. Run cat_file.exe, when prompted for a filename, type '_exploit.txt_'

6. Observe the calc.exe program start.

Change the shellcode in the exploit.py to run any other code. The exploit.py will adjust the size of the overflow buffer to ensure the correct EIP is set.
